export const COLOURS = {
    white: '#ffffff',
    black: '#000000',
    green: '#00AC76',
    red: '#C04345',
    blue: '#0043F9',
    backgroundLight: '#F0F0F3',
    backgroundMedium: '#B9B9B9',
    backgroundDark: '#777777',
  };

  export const Items = [
    {
      id: 1,
      category: 'product',
      productName: 'Bơ Mỹ , Bơ Dẻo Ngon Vị Phô Mai',
      productPrice: 10,
      description:
        'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai, ',
      isOff: true,
      offPercentage: 10,
      productImage: require('../database/images/products/shirt1.jpg'),
      isAvailable: true,
      productImageList: [
        require('../database/images/products/shirt1.jpg'),
        require('../database/images/products/shirt2.jpg'),
        require('../database/images/products/shirt3.jpg'),
      ],
    },
    {
        id: 2,
        category: 'product',
        productName: 'Bơ Mỹ , Bơ Dẻo Ngon Vị Phô Mai',
        productPrice: 1499,
        description:
        'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai, ',
        isOff: true,
        offPercentage: 10,
        productImage: require('../database/images/products/shirt2.jpg'),
        isAvailable: true,
        productImageList: [
          require('../database/images/products/shirt1.jpg'),
          require('../database/images/products/shirt2.jpg'),
          require('../database/images/products/shirt3.jpg'),
        ],
      },
      {
        id: 3,
        category: 'accessory',
        productName: 'Bơ Mỹ , Bơ Dẻo Ngon Vị Phô Mai',
        productPrice: 599,
        description:
        'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai, ',
        isOff: true,
        offPercentage: 10,
        productImage: require('../database/images/products/shirt3.jpg'),
        isAvailable: true,
        productImageList: [
          require('../database/images/products/shirt1.jpg'),
          require('../database/images/products/shirt2.jpg'),
          require('../database/images/products/shirt3.jpg'),
        ],
      },
      {
        id: 4,
        category: 'accessory',
        productName: 'Bơ Mỹ , Bơ Dẻo Ngon Vị Phô Mai',
        productPrice: 799,
        description:
          'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai',
        isOff: true,
        offPercentage: 10,
        productImage: require('../database/images/products/shirt4.jpg'),
        isAvailable: true,
        productImageList: [
          require('../database/images/products/shirt1.jpg'),
          require('../database/images/products/shirt2.jpg'),
          require('../database/images/products/shirt3.jpg'),
        ],
      },
      {
        id: 5,
        category: 'accessory',
        productName: 'hoa quả',
        productPrice: 999,
        description:
          'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
        isOff: true,
        offPercentage: 10,
        productImage: require('../database/images/products/pants1.jpg'),
        isAvailable: true,
        productImageList: [
          require('../database/images/products/shirt1.jpg'),
          require('../database/images/products/shirt2.jpg'),
          require('../database/images/products/shirt3.jpg'),
        ],
      },
      {
        id: 6,
        category: 'accessory',
        productName: 'trái cam',
        productPrice: 199,
        description:
          'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
        isOff: true,
        offPercentage: 10,
        productImage: require('../database/images/products/pants2.jpg'),
        isAvailable: true,
        productImageList: [
          require('../database/images/products/shirt1.jpg'),
          require('../database/images/products/shirt2.jpg'),
          require('../database/images/products/shirt3.jpg'),
        ],
      },
      {
      id: 7,
        category: 'accessory',
        productName: 'trái cam',
        productPrice: 199,
        description:
          'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
        isOff: true,
        offPercentage: 10,
        productImage: require('../database/images/products/pants2.jpg'),
        isAvailable: true,
        productImageList: [
          require('../database/images/products/shirt1.jpg'),
          require('../database/images/products/shirt2.jpg'),
          require('../database/images/products/shirt3.jpg'),
        ],
      },
      {
        id: 8,
          category: 'accessory',
          productName: 'trái cam',
          productPrice: 199,
          description:
            'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
          isOff: true,
          offPercentage: 10,
          productImage: require('../database/images/products/pants2.jpg'),
          isAvailable: true,
          productImageList: [
            require('../database/images/products/shirt1.jpg'),
            require('../database/images/products/shirt2.jpg'),
            require('../database/images/products/shirt3.jpg'),
          ],
        },
        {
          id: 8,
            category: 'product',
            productName: 'trái cam',
            productPrice: 199,
            description:
              'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
            isOff: true,
            offPercentage: 10,
            productImage: require('../database/images/products/pants2.jpg'),
            isAvailable: true,
            productImageList: [
              require('../database/images/products/shirt1.jpg'),
              require('../database/images/products/shirt2.jpg'),
              require('../database/images/products/shirt3.jpg'),
            ],
          },
          {
            id: 9,
              category: 'accessory',
              productName: 'trái cam',
              productPrice: 199,
              description:
                'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
              isOff: true,
              offPercentage: 10,
              productImage: require('../database/images/products/pants2.jpg'),
              isAvailable: true,
              productImageList: [
                require('../database/images/products/shirt1.jpg'),
                require('../database/images/products/shirt2.jpg'),
                require('../database/images/products/shirt3.jpg'),
              ],
            },
            {
              id: 10,
                category: 'accessory',
                productName: 'trái cam',
                productPrice: 199,
                description:
                  'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                isOff: true,
                offPercentage: 10,
                productImage: require('../database/images/products/pants2.jpg'),
                isAvailable: true,
                productImageList: [
                  require('../database/images/products/shirt1.jpg'),
                  require('../database/images/products/shirt2.jpg'),
                  require('../database/images/products/shirt3.jpg'),
                ],
              }, 
              {
                id: 11,
                  category: 'accessory',
                  productName: 'trái cam',
                  productPrice: 199,
                  description:
                    'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                  isOff: true,
                  offPercentage: 10,
                  productImage: require('../database/images/products/pants2.jpg'),
                  isAvailable: true,
                  productImageList: [
                    require('../database/images/products/shirt1.jpg'),
                    require('../database/images/products/shirt2.jpg'),
                    require('../database/images/products/shirt3.jpg'),
                  ],
                }, 
                {
                  id: 12,
                    category: 'accessory',
                    productName: 'trái cam',
                    productPrice: 199,
                    description:
                      'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                    isOff: true,
                    offPercentage: 10,
                    productImage: require('../database/images/products/pants2.jpg'),
                    isAvailable: true,
                    productImageList: [
                      require('../database/images/products/shirt1.jpg'),
                      require('../database/images/products/shirt2.jpg'),
                      require('../database/images/products/shirt3.jpg'),
                    ],
                  }, 
                  {
                    id: 13,
                      category: 'accessory',
                      productName: 'trái cam',
                      productPrice: 199,
                      description:
                        'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                      isOff: true,
                      offPercentage: 10,
                      productImage: require('../database/images/products/pants2.jpg'),
                      isAvailable: true,
                      productImageList: [
                        require('../database/images/products/shirt1.jpg'),
                        require('../database/images/products/shirt2.jpg'),
                        require('../database/images/products/shirt3.jpg'),
                      ],
                    }, 
                    {
                      id: 14,
                        category: 'accessory',
                        productName: 'trái cam',
                        productPrice: 199,
                        description:
                          'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                        isOff: true,
                        offPercentage: 10,
                        productImage: require('../database/images/products/pants2.jpg'),
                        isAvailable: true,
                        productImageList: [
                          require('../database/images/products/shirt1.jpg'),
                          require('../database/images/products/shirt2.jpg'),
                          require('../database/images/products/shirt3.jpg'),
                        ],
                      }, 
                      {
                        id: 15,
                          category: 'accessory',
                          productName: 'trái cam',
                          productPrice: 199,
                          description:
                            'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                          isOff: true,
                          offPercentage: 10,
                          productImage: require('../database/images/products/pants2.jpg'),
                          isAvailable: true,
                          productImageList: [
                            require('../database/images/products/shirt1.jpg'),
                            require('../database/images/products/shirt2.jpg'),
                            require('../database/images/products/shirt3.jpg'),
                          ],
                        }, 
                        {
                          id: 16,
                            category: 'accessory',
                            productName: 'trái cam',
                            productPrice: 199,
                            description:
                              'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                            isOff: true,
                            offPercentage: 10,
                            productImage: require('../database/images/products/pants2.jpg'),
                            isAvailable: true,
                            productImageList: [
                              require('../database/images/products/shirt1.jpg'),
                              require('../database/images/products/shirt2.jpg'),
                              require('../database/images/products/shirt3.jpg'),
                            ],
                          }, 
                          {
                            id: 17,
                              category: 'accessory',
                              productName: 'trái cam',
                              productPrice: 199,
                              description:
                                'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                              isOff: true,
                              offPercentage: 10,
                              productImage: require('../database/images/products/pants2.jpg'),
                              isAvailable: true,
                              productImageList: [
                                require('../database/images/products/shirt1.jpg'),
                                require('../database/images/products/shirt2.jpg'),
                                require('../database/images/products/shirt3.jpg'),
                              ],
                            }, 
                            {
                              id: 18,
                                category: 'accessory',
                                productName: 'trái cam',
                                productPrice: 199,
                                description:
                                  'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                                isOff: true,
                                offPercentage: 10,
                                productImage: require('../database/images/products/pants2.jpg'),
                                isAvailable: true,
                                productImageList: [
                                  require('../database/images/products/shirt1.jpg'),
                                  require('../database/images/products/shirt2.jpg'),
                                  require('../database/images/products/shirt3.jpg'),
                                ],
                              }, 
                              {
                                id: 19,
                                  category: 'accessory',
                                  productName: 'trái cam',
                                  productPrice: 199,
                                  description:
                                    'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                                  isOff: true,
                                  offPercentage: 10,
                                  productImage: require('../database/images/products/pants2.jpg'),
                                  isAvailable: true,
                                  productImageList: [
                                    require('../database/images/products/shirt1.jpg'),
                                    require('../database/images/products/shirt2.jpg'),
                                    require('../database/images/products/shirt3.jpg'),
                                  ],
                                }, 
                                {
                                  id: 20,
                                    category: 'accessory',
                                    productName: 'trái cam',
                                    productPrice: 199,
                                    description:
                                      'Miêu tả: trái cây tươi Bơ siêu ngon, thịt bơ màu vàng kem, độ dẻo vừa phải, mùi thơm và độ béo cao, có vị mặn nhẹ phomai.',
                                    isOff: true,
                                    offPercentage: 10,
                                    productImage: require('../database/images/products/pants2.jpg'),
                                    isAvailable: true,
                                    productImageList: [
                                      require('../database/images/products/shirt1.jpg'),
                                      require('../database/images/products/shirt2.jpg'),
                                      require('../database/images/products/shirt3.jpg'),
                                    ],
                                  }, 
                                 
                
  ]

